name: Update papers.json

on:
  schedule:
    # Runs at midnight UTC
    - cron:  '0 0 * * *'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the script
      run: python extract.py  # Runs your Python script

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add papers.json  # Add the updated JSON file
        git commit -m "Update papers.json" -a || echo "No changes to commit"
        git push
